### ISSUE TITLE
request to fix NERSC permissions to full dataset

### ISSUE THREAD

**Issue by moustakas** [georgestein/ssl-legacysurvey#1]
I'd like to access the full dataset at NERSC (not through the Globus endpoint, to avoid duplicating data), but the permissions are too restrictive (note that I intentionally changed `/global/cfs/projectdirs` to `/global/cfs/cdirs` since `projectdirs` is deprecated):

```
% ls -l /global/cfs/cdirs/cusp/LBL/decals_galaxy_survey/
ls: cannot access '/global/cfs/cdirs/cusp/LBL/decals_galaxy_survey/': Permission denied

% ls -ld /global/cfs/cdirs/cusp/LBL
drwxrws--- 8 zarija cusp 4096 Dec 16  2021 /global/cfs/cdirs/cusp/LBL
```

Thank you!

**Comment by georgestein** [comment]
Hey John, good point! I should have made them available to NERSC users without going through Globus.

Unfortunately I am no longer an active member of NERSC to fix this tho.

@pzharrington any chance you have permissions to do this?

**Comment by pzharrington** [comment]
@georgestein I think I can go in and fix this -- you just want me to make `/global/cfs/cdirs/cusp/LBL/decals_galaxy_survey` world-readable?

**Comment by georgestein** [comment]
@pzharrington I believe this is all that is required (just double check that is where the data is actually located!). So NERSC people don't have to download a copy through globus

**Comment by pzharrington** [comment]
Ok I can do this -- under `decals_galaxy_survey` I see the following:
```
drwxrwx---  7 gstein   cusp       4096 Sep 16  2021 catalogues
drwxrwx---  5 gstein   cusp       4096 Dec  2  2021 external_catalogues
drwxrwx---  4 gstein   cusp       4096 Jun  4  2021 figures
drwxrwx---  5 gstein   gstein   262144 May  5  2021 imagenet1k
drwxrwx---  6 gstein   cusp       4096 Jun  7  2022 images
drwxrwx---  3 gstein   cusp       4096 Jun 21  2021 linear_classifiers
drwxrwx---  9 gstein   gstein     4096 Nov 19  2021 moco_clone
drwxrwx---  4 gstein   cusp       4096 Aug 24  2021 notebooks
drwxrwx--- 11 gstein   gstein    16384 Feb  4  2022 random
drwxrwx---  6 gstein   cusp      16384 Oct  5  2021 representations
drwxrwx---  4 gstein   cusp       4096 Feb 23  2021 sdss_dataset
drwxrwx---  2 pharring pharring   4096 Jun 29  2021 splits
drwxrwx---  2 gstein   cusp       4096 Jun 29  2021 src
drwxrwx---  7 gstein   gstein     4096 Apr 15  2022 strong_lensing_paper
drwxrwx---  8 gstein   cusp      16384 Jun  9  2022 tmp
drwxrwx---  4 gstein   gstein     4096 Jun  7  2022 unorganized_data
drwxrwx---  3 pharring pharring   4096 Jul 16  2021 vissl
```
Do we want to open up just the `images` folder, as in the globus portal, or everything? For now I opened up `images`, so it should be accessible to you @moustakas.

**Comment by moustakas** [comment]
Thanks @pzharrington, but the top-level `LBL` directory still lacks sufficient permissions for me to see the lower-level contents.
```
ls -ld /global/cfs/cdirs/cusp/LBL
drwxrws--- 8 zarija cusp 4096 Dec 16  2021 /global/cfs/cdirs/cusp/LBL
```

**Comment by moustakas** [comment]
And to clarify, we would like the images as well as the trained models. The documentation (https://github.com/georgestein/ssl-legacysurvey) states:
```
Self-supervised models are released as pytorch checkpoints, in order to see the training/hyperparameter 
setup used. They can be found at the Globus endpoint described above.
```
But I'm not sure which subdirectory these are located in.

**Comment by georgestein** [comment]
Just make the images/ folder public if possible.

Hm if the models are not there I don't know where they would be. Maybe they never got ported over from the old location... Very frustrating that I can no longer login to investigate this!

**Comment by moustakas** [comment]
> Hm if the models are not there I don't know where they would be. Maybe they never got ported over from the old location... Very frustrating that I can no longer login to investigate this!

Is this something you'd be able to confirm somehow? We were optimistic that we would be able to make lots of progress using the existing models but it sounds like we'll need to do the training ourselves first. Regardless, we're truly grateful for all the code and data you've made public!

**Comment by pzharrington** [comment]
Hi @moustakas -- apologies for the confusion. We got mixed up about which paths were used for mirroring the Globus sharing portal. I have added `trained_models/resnet50.ckpt` to the Globus sharing directory, so now it should be available via the Globus interface. Also, if you want to access the model checkpoint and the data directly on NERSC CFS disk then you should be able to access them in the following directory:
```
> ls -al /global/cfs/cdirs/cusp/gsharing/ssl-legacysurvey
total 4
drwxr-xr-x 4 gstein cusp   4096 Jun 12 13:07 .
drwxr-xr-x 3 gstein cusp   4096 Jun 12 13:07 ..
drwxr-xr-x 6 gstein cusp   4096 Jun  9  2022 images
drwxrwxr-x 2 gstein gstein 4096 Jun 12 13:07 trained_models
```

**Comment by moustakas** [comment]
We've confirmed that we can read all the files we need, @pzharrington, thank you! (And many thanks to @georgestein as well.)
